# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function that builds Battlegrounds hero stats on a regular schedule

Resources:
    BuildHourlyHeroStats2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: solo/hourly/_build-battlegrounds-hero-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/solo/hourly/_build-battlegrounds-hero-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 5
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-hourly-bgs-hero-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        # Cron that runs every hour at 10 minutes past the hour
                        Schedule: cron(30 * * * ? *)
    AggregateHourlyHeroStats2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: solo/aggregate-hourly/heroes/_build-aggregated-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/solo/aggregate-hourly/heroes/_build-aggregated-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 15
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-hourly-bgs-hero-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(55 * * * ? *)
    AggregateHourlyQuestStats2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: solo/aggregate-hourly/quests/_build-aggregated-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/solo/aggregate-hourly/quests/_build-aggregated-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-hourly-bgs-quest-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(50 * * * ? *)
    AggregateHourlyTrinketStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: solo/aggregate-hourly/trinkets/_build-aggregated-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/solo/aggregate-hourly/trinkets/_build-aggregated-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-hourly-bgs-trinkets-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(50 * * * ? *)

    BuildHourlyHeroStatsDuos:
        Type: AWS::Serverless::Function
        Properties:
            Handler: duos/hourly/_build-battlegrounds-hero-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/duos/hourly/_build-battlegrounds-hero-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 5
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-hourly-bgs-hero-stats-duos
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        # Cron that runs every hour at 10 minutes past the hour
                        Schedule: cron(20 * * * ? *)
    AggregateHourlyHeroStatsDuos:
        Type: AWS::Serverless::Function
        Properties:
            Handler: duos/aggregate-hourly/heroes/_build-aggregated-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/duos/aggregate-hourly/heroes/_build-aggregated-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 15
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-hourly-bgs-hero-stats-duos
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(45 * * * ? *)
